var child = [
  { 'dupe': false, 'type': 64, 'name': 'action=login_do', 'dir': 'c0', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=login_do&login=skipfish&password=skipfish', 'fetched': true, 'code': 200, 'len': 2979, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 2, 0, 0 ], 'sig': 0xad282ddf },
  { 'dupe': false, 'type': 64, 'name': 'email=skipfish@example.com', 'dir': 'c1', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=register_do&login=skipfish&email=skipfish@example.com&password=skipfish&password_confirm=skipfish&sex=1&news=on', 'fetched': true, 'code': 200, 'len': 3926, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0xffbe8877 },
  { 'dupe': false, 'type': 64, 'name': 'login=skipfish', 'dir': 'c2', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=login_do&login=skipfish&password=skipfish', 'fetched': true, 'code': 200, 'len': 2979, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 1, 0 ], 'sig': 0x8038c20 },
  { 'dupe': false, 'type': 64, 'name': 'news=on', 'dir': 'c3', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=register_do&login=skipfish&email=skipfish@example.com&password=skipfish&password_confirm=skipfish&sex=1&news=on', 'fetched': true, 'code': 200, 'len': 3926, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0xffbe8877 },
  { 'dupe': false, 'type': 64, 'name': 'password=skipfish', 'dir': 'c4', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=login_do&login=skipfish&password=skipfish', 'fetched': true, 'code': 200, 'len': 2979, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffbfffff },
  { 'dupe': false, 'type': 64, 'name': 'password_confirm=skipfish', 'dir': 'c5', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=register_do&login=skipfish&email=skipfish@example.com&password=skipfish&password_confirm=skipfish&sex=1&news=on', 'fetched': true, 'code': 200, 'len': 3926, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0xffbe8877 },
  { 'dupe': false, 'type': 64, 'name': 'sex=1', 'dir': 'c6', 'linked': 5, 'url': 'http://test.mutc.ru/cgi-bin/bug.pl DATA:action=register_do&login=skipfish&email=skipfish@example.com&password=skipfish&password_confirm=skipfish&sex=1&news=on', 'fetched': true, 'code': 200, 'len': 3926, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x6b1aa1bc }
];
